/* See LICENSE file for license and copyright information */

#ifndef PREFETCH_PROFILE_MODULE_H
#define PREFETCH_PROFILE_MODULE_H

#define PREFETCH_PROFILE_DEVICE_NAME "prefetch-profile"
#define PREFETCH_PROFILE_DEVICE_PATH "/dev/" PREFETCH_PROFILE_DEVICE_NAME

#define PREFETCH_PROFILE_IOCTL_MAGIC_NUMBER (long) 'x'

#define PREFETCH_PROFILE_IOCTL_CMD_ACCESS_ADDRESS _IOR(PREFETCH_PROFILE_IOCTL_MAGIC_NUMBER, 1, size_t)

#endif // PREFETCH_PROFILE_MODULE_H
