/* See LICENSE file for license and copyright information */

#ifndef KERNEL_SPECTRE_MODULE_H
#define KERNEL_SPECTRE_MODULE_H

#define KERNEL_SPECTRE_DEVICE_NAME "kernel_spectre"
#define KERNEL_SPECTRE_DEVICE_PATH "/dev/" KERNEL_SPECTRE_DEVICE_NAME
#define KERNEL_SPECTRE_SECRET_DATA "ABCSECRETSECRETSECRETSECRET";

#define KERNEL_SPECTRE_IOCTL_MAGIC_NUMBER (long) 'x'

#define KERNEL_SPECTRE_IOCTL_CMD_ACCESS _IOR(KERNEL_SPECTRE_IOCTL_MAGIC_NUMBER, 1, size_t)

#define KERNEL_SPECTRE_IOCTL_CMD_GET_ADDRESS _IOR(KERNEL_SPECTRE_IOCTL_MAGIC_NUMBER, 2, size_t)

#define KERNEL_SPECTRE_IOCTL_CMD_GET_MAPPING _IOR(KERNEL_SPECTRE_IOCTL_MAGIC_NUMBER, 3, size_t)

#endif // KERNEL_SPECTRE_MODULE_H
